USE [master]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OJT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OJT] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OJT] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OJT] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OJT] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OJT] SET ARITHABORT OFF 
GO

ALTER DATABASE [OJT] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [OJT] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OJT] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OJT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OJT] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OJT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OJT] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OJT] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OJT] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OJT] SET  DISABLE_BROKER 
GO

ALTER DATABASE [OJT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OJT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OJT] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OJT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OJT] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OJT] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OJT] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OJT] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [OJT] SET  MULTI_USER 
GO

ALTER DATABASE [OJT] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OJT] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OJT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OJT] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [OJT] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OJT] SET  READ_WRITE 
GO


